### ISSUE TITLE
Feature request : Modify the running time

### ISSUE THREAD

**Issue by Kohulan** [OBrink/Impfcheck_Thueringen#1]
Hi Otto,

Running the code continuously for 10 hours and pinging the server every 10 minutes could lead to banning. Add a new function to create random time stamps, and execute the script on that time stamp. The code can simply run in the background the whole day.

-Kohulan

**Comment by OBrink** [comment]
Hey Kohulan,

Nice idea! I don't seem to get blocked when it is accessing the page exactly every 10 minutes but you are right. I have changed it so that it runs the check at a random time every 5-15 minutes. Thank you for the suggestion!

-Otto
